name: Jest Testing

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.9.1

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGO_PRODUCTION_URL: ${{ secrets.MONGO_PRODUCTION_URL }}
          MONGO_TEST_URL: ${{ secrets.MONGO_TEST_URL }}

      - name: Run Jest tests
        run: npm test
