name: Jest Testing

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.9.1

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start &

      - name: Wait for server to start
        run: sleep 10

      - name: Set up environment variables
        run: |
          echo "JWT_SECRET=$JWT_SECRET" >> $GITHUB_ENV
          echo "MONGO_PRODUCTION_URL=$MONGO_PRODUCTION_URL" >> $GITHUB_ENV
          echo "MONGO_TEST_URL=$MONGO_TEST_URL" >> $GITHUB_ENV

      - name: Run Jest tests
        run: npm test
